name: crystallis_example
description: Example for crystallis
version: 0.0.1

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crystallis:
    path: ../

dev_dependencies:
  build_runner: ^2.10.5
  source_gen: ^4.2.0
  build: ^4.0.4
