name: crystallis
description: ðŸ’ âœ¨ Data class codegen w/ validation & runtime metadata for Dart
version: 0.0.1
repository: https://github.com/kerberjg/crystallis.dart
license: MPL-2.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.9.0

dev_dependencies:
  build: ^4.0.4
  build_test: ^3.5.5
  source_gen: ^4.2.0
  analyzer: ^10.0.1
  test: ^1.29.0