name: crystallis
description: ðŸ’ âœ¨ Data class codegen w/ validation & runtime metadata for Dart
version: 0.0.1
repository: https://github.com/kerberjg/crystallis.dart
license: MPL-2.0

environment:
  sdk: ">=3.6.0 <4.0.0"

resolution: workspace

dependencies:
  meta: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.29.0