name: crystallis_generator
description: ðŸ’ âœ¨ Codegen utility for the Crysallis package
version: 0.0.1
repository: https://github.com/kerberjg/crystallis.dart
license: MPL-2.0

environment:
  sdk: ">=3.6.0 <4.0.0"

resolution: workspace

dependencies:
  analyzer: ^10.0.1
  build: ^4.0.4
  meta: ^1.9.0
  source_gen: ^4.2.0
  crystallis: 0.0.1

dev_dependencies:
  build_test: ^3.5.5
  lints: ^6.0.0
  test: ^1.29.0